### ISSUE TITLE
SOLR Comunication problem?

### ISSUE THREAD

**Issue by Vytek** [aegif/NemakiWare#189] opened 2016-02-07 16:08 UTC
Entering in new setup I see this error on SOLR logging:

ERROR
NemakiTokenManager
Cannot connect to Core REST API
16:56:36
ERROR
NemakiTokenManager
Cannot connect to Core REST API
16:57:15
ERROR
CmisSessionFactory
Failed to create a session to CMIS server
16:57:15
WARN
CmisSessionFactory
No CMIS repositoryId:canopy
16:57:17
ERROR
JobRunShell
Job Solr.CoreTrackerJob threw an unhandled Exception:
16:57:17
ERROR
ErrorLogger
Job (Solr.CoreTrackerJob threw an exception.

I setup a new installation 2 times. Where is the error? I am using a DigitalOcean Server with 1 G of RAM and 30 G HD. Please help me!
Regards.

**Comment by linzhixing** [comment] 2016-02-07 16:17
Probably it is caused by NemakiTokenManager, which is used to publish authentication tokens for improving performance.

Known bug: Solr tries to get auth token by wrong parameter

I have already committed fec7ff744b53281d601916b795a77155749891fc for the next release version(2.3.9), though I've not confirmed the above error.

**Comment by Vytek** [comment] 2016-02-07 17:55
Thank you!

Can you release a new 2.3.9 versione installer?

**Comment by linzhixing** [comment] 2016-03-02 08:47
@Vytek 
We've now released 2.3.10, including the fix above.
https://github.com/aegif/NemakiWare/releases/tag/2.3.10

Can you try this?

**Closed** 2016-03-22 06:24 UTC
Labels: bug

**Comment by Vytek** [comment] 2016-03-22 16:35
Sorry for the delay!

Reinstall all another error:

22-Mar-2016 12:02:51.022 SEVERE [http-nio-8080-exec-3] com.sun.xml.ws.transport.http.HttpAdapter$HttpToolkit.handle Couldn't create SOAP message due to exception: org.$
 com.sun.xml.ws.protocol.soap.MessageCreationException: Couldn't create SOAP message due to exception: org.jvnet.mimepull.MIMEParsingException: Reached EOF, but there $
        at com.sun.xml.ws.encoding.SOAPBindingCodec.decode(SOAPBindingCodec.java:365)
        at com.sun.xml.ws.transport.http.HttpAdapter.decodePacket(HttpAdapter.java:277)
        at com.sun.xml.ws.transport.http.HttpAdapter.access$500(HttpAdapter.java:93)
        at com.sun.xml.ws.transport.http.HttpAdapter$HttpToolkit.handle(HttpAdapter.java:457)
        at com.sun.xml.ws.transport.http.HttpAdapter.handle(HttpAdapter.java:244)
        at com.sun.xml.ws.transport.http.servlet.ServletAdapter.handle(ServletAdapter.java:135)
        at com.sun.xml.ws.transport.http.servlet.WSServletDelegate.doGet(WSServletDelegate.java:129)
        at com.sun.xml.ws.transport.http.servlet.WSServletDelegate.doPost(WSServletDelegate.java:160)
        at com.sun.xml.ws.transport.http.servlet.WSServlet.doPost(WSServlet.java:75)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
        at org.apache.chemistry.opencmis.server.impl.webservices.CmisWebServicesServlet.service(CmisWebServicesServlet.java:154)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:217)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:673)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
